<?php

require_once __DIR__ . '/../vendor/autoload.php';
require_once __DIR__ . '/../src/EntityGenerator/EntityGenerator.php';
use EntityGenerator\EntityGenerator;

if (array_key_exists('table', $_POST)) {
  // let's do something
  $zf2Mapper = new EntityGenerator;
  $output = $zf2Mapper->create($_POST['table'], $_POST['columns']);
  
}

?>
<html>
  <head>
    <title>Let's format something</title>
  </head>
  <body>
    <form method="post">
    Table name: <input type="text" name="table" placeholder="Table" 
        <?php if(isset($_POST['table'])) : ?>value="<?php echo $_POST['table']; ?>" <?php endif; ?>>
    <br/>
    Place here your MYSQL output from EXPLAIN (only first 2 columns)<br/>
    <textarea rows="10" cols="50" name="columns"><?php if(isset($_POST['columns'])) : echo $_POST['columns']; endif; ?></textarea>
	 <input type="submit">
    </form>
    <hr>
    <?php 
	if(isset($output)): 
	foreach($output as $file => $content) :
	?>
	<h2><?php echo $file; ?></h2>
	<textarea rows="10" cols="50"><?php echo $content; ?></textarea>
	<?php endforeach;
	endif; ?>
  </body>
    
</html>